---
driver:
  name: vagrant

provisioner:
  name: chef_solo

platforms:
  - name: ubuntu-14.04

suites:
  - name: standard
    run_list:
      - recipe[shipyard_test::agent_standard]
    attributes:
  - name: container
    run_list:
      - recipe[shipyard_test::agent_container]
