---
driver:
  name: vagrant

provisioner:
  name: chef_solo

platforms:
  - name: ubuntu-14.04

suites:
  - name: standard
    run_list:
      - recipe[shipyard::agent]
    attributes:
  - name: container
    run_list:
      - recipe[shipyard::agent]
    attributes:
      shipyard:
        agent:
          install_type: container
